
<table id="head" cellpadding="0" cellspacing="0">
	<tr>
		<td id="logo" valign="bottom">
			<img src="images/clientsolutionsLogo.png" />
        </td>
        <td id="apps" align="right" valign="top">
			<ul>
				<li><a title="Eloqua" href="https://secure.eloqua.com" target="_blank"><img src="images/eloqua.png" /></a></li>
				<li><a title="Topliners" href="http://topliners.eloqua.com" target="_blank"><img src="images/top.png" /></a></li>
				<li><a title="DDC7" href="https://login.na.epidm.net/ddc7" target="_blank"><img src="images/dm7.png" /></a></li>
				<li><a title="DDC4" href="https://login.na.epidm.net/ddc4" target="_blank"><img src="images/dm4.png" /></a></li>				
			    <li><a title="Toggl" href="http://www.toggl.com" target="_blank"><img src="images/togglsm.png" /></a></li>
				<li><a title="World Clock" href="http://www.worldtimebuddy.com/?lid=1880252,2643743,5128581,4887398,5419384,5391959&h=4887398" target="_blank"><img src="images/wtbsm.png" /></a></li>	
                <li><a title="eOrders" href="https://docs.google.com/spreadsheet/ccc?key=0AiUH_dItKmrEdC1USjIzODRoa2h0cjAwb3p1WWIzVXc#gid=0" target="_blank"><img src="images/docs.png" /></a></li>							
        	</ul>
			
        </td>
    </tr>
</table>
            

        	